package com.factset.sdk.eventdriven.factsettrading.model.enums;

public enum IdSource {
    cusip,
    sedol,
    quik,
    isinNumber,
    ricCode,
    isoCurrencyCode,
    isoCountryCode,
    exchangeSymbol,
    consolidatedTapeAssociation,
    bloombergSymbol,
    wertpapier,
    dutch,
    valoren,
    sicovam,
    belgian,
    common,
    clearingHouse,
    isdaFpMLSpecification,
    optionPriceReportingAuthority,
    isdaFpMLURL,
    letterOfCredit,
    marketplaceAssignedIdentifier,
    markitREDEntityCLIP,
    markitREDPairCLIP,
    cftcCommodityCode,
    isdaCommodityReferencePrice,
    financialInstrumentGlobalIdentifier,
    legalEntityIdentifier,
    synthetic,
    fidessaInstrumentMnemonic,
    indexName,
    uniformSymbol,
    digitalTokenIdentifier
}
